id: 55f3b64865074ae5b880f71625ebd47c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_438-Tara_with_Twenty-One_Verses_of_Homage-v2
  language: bo
  author: ''
  volume: {}
